    -- Database setup script for Smart Money Tracking

    -- Create database (run this in PostgreSQL)
    CREATE DATABASE smart_money_tracking;

    -- Connect to the database
    \c smart_money_tracking;

    -- Users table will be auto-generated by Hibernate
    -- But here's the expected schema for reference:

    -- CREATE TABLE users (
    --     id BIGSERIAL PRIMARY KEY,
    --     name VARCHAR(255) NOT NULL,
    --     email VARCHAR(255) UNIQUE NOT NULL,
    --     password VARCHAR(255) NOT NULL,
    --     phone VARCHAR(50),
    --     is_enabled BOOLEAN NOT NULL DEFAULT true,
    --     created_at TIMESTAMP NOT NULL,
    --     updated_at TIMESTAMP
    -- );

    -- Create index for faster email lookup
    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
